### ISSUE TITLE
Waterlogged blocks

### ISSUE THREAD

**Issue by Jon1Games** [JanTomFoerster/FishingExtendet#1]
If a waterlogged block is encountered while obtaining the position for the billboard, it will come to a halt and spawn the billboard in the water.

This function can be used to check for waterlogged blocks:
[https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/block/data/Waterlogged.html](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/block/data/Waterlogged.html)

**Comment by JanTomFoerster** [comment]
Fixed by adding a method to check for specific blocks like Kelp.
Also moved watter in that function to clean up the code.
